package edu.coen390.androidapp.Model;

public enum Source {
    CARDSCAN_ACTIVITY,
    COURSE_ACTIVITY,
    INVIGILATOR_ACTIVITY,
    INVIGILATORREPORT_ACTIVITY,
    LIVEFEED_ACTIVITY,
    LOGIN_ACTIVITY,
    MANUALVERIFICATION_ACTIVITY,
    PROFESSOR_ACTIVITY,
    PROFESSORREPORT_ACTIVITY
}